# Generated by Django 3.0.4 on 2020-03-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200330_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
